export type CoinMarketInfo = {
  id: string
  symbol: string
  name: 'Bitcoin'
  image: 'https://assets.coingecko.com/coins/images/1/large/bitcoin.png?1547033579'
  currentPrice: number
  marketCap: number
  marketCapRank: number
  fullyDilutedValuation: number
  totalVolume: number
  high24h: number
  low24h: number
  priceChange24h: number
  priceChangePercentage24h: number
  marketCapChange24h: number
  marketCapChangePercentage24h: number
  circulatingSupply: number
  totalSupply: number
  maxSupply: number
  ath: number
  athChangePercentage: number
  athDate: string
  atl: number
  atlChangePercentage: number
  atlDate: string
  lastUpdated: string
  priceChangePercentage1hInCurrency: number
  priceChangePercentage24hInCurrency: number
  priceChangePercentage7dInCurrency: number
}
